server:
  port: 7777

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8888/eureka


spring:
  application:
    name: proxy
  cloud:
    gateway:
      routes:
        - id: routetouser
          predicates:
            - Path=/cloud/user/**
          filters:
            - RewritePath=/cloud/user/(?<s>.*), /${s}

          uri: lb://ms-user
        - id: routetoserver
          predicates:
            - Path=/cloud/server/**
          filters:
            - RewritePath=/cloud/server/(?<s>.*), /${s}
          uri: lb://ms-server
